# https://travis-ci.org/repositories
# http://docs.travis-ci.com/user/customizing-the-build/
# http://docs.travis-ci.com/user/installing-dependencies/

language: python
python: 2.7

# Use the new container-based infrastructure
# Note: Can not use apt-get install with this setup
# Workaround: addons.apt.packages and addons.apt.sources
sudo: false

install:
  - pip install -r requirements.txt
  - npm install -g --production less

before_script:
  - sh mkdirs.sh ; true
  - django/manage.py migrate

script:
  - make test
