# https://travis-ci.org/repositories
# http://docs.travis-ci.com/user/customizing-the-build/
# http://docs.travis-ci.com/user/installing-dependencies/

language: python
python: 2.7

install:
  - pip install -r requirements.txt
  - npm install -g --production less

before_script:
  - sh mkdirs.sh
  - django/manage.py migrate

script:
  - make test
