# Tools for routine tasks

# export:
# python manage.py dumpdata files

# import:
# python manage.py loaddata fixtures/initial_data.yaml

# python manage.py dumpdata --format=xml flatpages | xml fo >
#   fixtures/flatpages.xml

# python manage.py loaddata fixtures/flatpages.xml

# This did not auto load with syncdb
# apps/flatpages/fixtures/initial_data.xml
# But it worked with own app:
# apps/news/fixtures/initial_data.json
